CREATE TABLE `test_results` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `user_id` INT UNSIGNED NOT NULL, `email` VARCHAR(100) CHARSET ASCII NOT NULL, `testdate` DATETIME, `subject` VARCHAR(255) CHARSET utf8, `header` TEXT CHARSET utf8, `content` TEXT, `score` FLOAT NOT NULL DEFAULT 0, `sender` VARCHAR(100) CHARSET ASCII, `created_at` DATETIME DEFAULT NOW(), `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`) ) CHARSET=utf8; 
ALTER TABLE `test_results` ADD COLUMN `name` VARCHAR(100) CHARSET utf8 NOT NULL AFTER `email`; 
ALTER TABLE `test_results` ADD COLUMN `mail_id` INT NOT NULL AFTER `id`; 

ALTER TABLE `test_results` ADD COLUMN `received_at` DATETIME NULL AFTER `name`, CHANGE `testdate` `tested_at` DATETIME NULL; 