CREATE TABLE `mail_blacklist_checks` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `mail_id` INT UNSIGNED NOT NULL, `cron_number` TINYINT UNSIGNED NOT NULL DEFAULT 0, `checkflag` TINYINT UNSIGNED NOT NULL DEFAULT 1, `created_at` DATETIME NOT NULL DEFAULT NOW(), `updated_at` TIMESTAMP NOT NULL DEFAULT NOW(), PRIMARY KEY (`id`) ) CHARSET=utf8; 
CREATE TABLE `blacklist_results` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `domain_key` VARCHAR(50) CHARSET ASCII NOT NULL, `domain_url` VARCHAR(50) CHARSET ASCII NOT NULL, `link_url` VARCHAR(255) CHARSET ASCII, `serverip` VARCHAR(20) CHARSET ASCII NOT NULL, `result` VARCHAR(255) CHARSET ASCII NOT NULL, `created_at` DATETIME DEFAULT NOW(), `updated_at` TIMESTAMP DEFAULT NOW(), PRIMARY KEY (`id`) ) CHARSET=utf8; 
CREATE TABLE `mail_brokenlink_checks` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `mail_id` INT UNSIGNED NOT NULL, `cron_number` TINYINT UNSIGNED NOT NULL DEFAULT 0, `checkflag` TINYINT NOT NULL DEFAULT 1, `created_at` DATETIME DEFAULT NOW(), `updated_at` TIMESTAMP DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`) ) CHARSET=utf8; 
CREATE TABLE `brokenlink_results` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `link_url` VARCHAR(255) NOT NULL, `result` VARCHAR(255), `created_at` DATETIME DEFAULT NOW(), `updated_at` TIMESTAMP DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`) ) CHARSET=utf8; 

ALTER TABLE `mail_blacklist_checks` CHANGE `updated_at` `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP NOT NULL, ADD INDEX (`mail_id`); 
ALTER TABLE `mail_brokenlink_checks` ADD INDEX (`mail_id`); 
ALTER TABLE `brokenlink_results` ADD COLUMN `header` VARCHAR(255) NULL AFTER `link_url`; 

ALTER TABLE `blacklist_results` ADD COLUMN `mark` FLOAT DEFAULT 0 NULL AFTER `result`; 
ALTER TABLE `brokenlink_results` ADD COLUMN `mark` FLOAT DEFAULT 0 NULL AFTER `result`; 

ALTER TABLE `brokenlink_results` CHANGE `header` `header` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;